name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators, simulators and real devices. Includes support for multiple locales and framing. Compatible with fastlane.
version: 2.1.1
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^1.6.0
  yaml: ^3.0.0
  resource: ^2.1.5
  path: ^1.6.2
  file: ^6.0.0
  archive: ^2.0.13
  platform: ^3.0.0
  process: ^4.0.0
  meta: ^1.1.6
  intl: 0.17.0
  tool_mobile:
    git: https://github.com/ventskus-roman/tool_mobile

dev_dependencies:
  test: ^1.16.5
  test_api: ^0.2.19
  mockito: ^4.1.4
  pedantic: ^1.8.0+1
  quiver: 3.0.1
  fake_process_manager:
    git: https://github.com/ventskus-roman/fake_process_manager
  tool_base_test:
    git: https://github.com/ventskus-roman/tool_base_test
  collection: any

dependency_overrides:
  archive: ^2.0.13

executables:
  screenshots: main