name: reporting
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  usage: 4.0.2
  tool_base:
    path: ../tool_base
#  tool_base:
#    path: ../tool_base
dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.16.5
  mockito: ^4.1.4
  tool_base_test:
    path: ../tool_base_test
  args: ^1.6.0
  quiver: ^3.0.1
  meta: ^1.1.8